backend:
  name: git-gateway

publish_mode: editorial_workflow
media_folder: static/uploads

collections:
  - name: "post"
    label: "Post"
    folder: "src/content"
    create: true
    slug: "{{slug}}"
    preview_path: "{{slug}}"
    editor:
     preview: true
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "relation", default: "Ghost"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Featured Image", name: "thumbnail", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list" }
